# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
dir(np.version)

['__annotations__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'full_version',
 'git_revision',
 'release',
 'short_version',
 'version']

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
a = np.random.random([3,2,5])
a

array([[[0.5463323 , 0.80534971, 0.91202668, 0.22581168, 0.24848961],
        [0.33873126, 0.99706522, 0.55147908, 0.16155328, 0.46631921]],

       [[0.65425205, 0.43198302, 0.75748205, 0.46181215, 0.85858557],
        [0.12753629, 0.62008195, 0.73212212, 0.22295423, 0.38581427]],

       [[0.19261981, 0.4467638 , 0.8876473 , 0.89751785, 0.73728934],
        [0.33261521, 0.70112362, 0.72985407, 0.26146965, 0.75726177]]])

In [9]:
a = np.empty((3,2,5))
a

array([[[0.5463323 , 0.80534971, 0.91202668, 0.22581168, 0.24848961],
        [0.33873126, 0.99706522, 0.55147908, 0.16155328, 0.46631921]],

       [[0.65425205, 0.43198302, 0.75748205, 0.46181215, 0.85858557],
        [0.12753629, 0.62008195, 0.73212212, 0.22295423, 0.38581427]],

       [[0.19261981, 0.4467638 , 0.8876473 , 0.89751785, 0.73728934],
        [0.33261521, 0.70112362, 0.72985407, 0.26146965, 0.75726177]]])

In [14]:
a = np.arange(30).reshape(3,2,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

#### 4. Print *a*.


In [ ]:
answer question 3

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [34]:
b = np.ones((5,2,3))


#### 6. Print *b*.


In [35]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [28]:
np.array_equal(a,b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [36]:
a+b
#no, they didn't have the same shape

ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [37]:
c = np.transpose(b)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
d=a+c
d

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]],

       [[11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.]],

       [[21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [42]:
a
d

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]],

       [[11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.]],

       [[21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [43]:
e = c*a
e

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [44]:
np.array_equal(e,a)

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [47]:
d_max=np.max(d)
d_max

30.0

In [48]:
d_min=np.min(d)
d_min

1.0

In [49]:
d_mean=np.mean(d)
d_mean

15.5

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [61]:
f = []
f =np.empty((3,2,5))
f


array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]],

       [[20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [62]:
for x in range(d.shape[0]):
        for y in range(d.shape[1]):
                for z in range(d.shape[2]):
                        if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                                f[x][y][z] = 25     
                        elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                                f[x][y][z] = 75    
                        elif d[x][y][z] == d_mean:
                                f[x][y][z] = 50     
                        elif (d_min) == d[x][y][z]:
                                f[x][y][z] = 0
                        elif (d_max) == d[x][y][z]:
                                f[x][y][z] = 100

print(f)

[[[  0.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 25.  25.  25.  25.  25.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here